### ISSUE TITLE
RuntimeError: CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by junedwx** [stevejpapad/Visual-InCompatibility-Transformer#4]
**When I trained the FLIP model, the following error was reported. **

> RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
> Process finished with exit code 1

**My environment is：**
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main
_openmp_mutex             5.1                       1_gnu
blas                      1.0                         mkl
ca-certificates           2023.01.10           h06a4308_0
certifi                   2022.12.7        py39h06a4308_0
charset-normalizer        3.1.0                    pypi_0    pypi
click                     8.1.3                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
cudatoolkit               11.3.1               h2bc3f7f_2
filelock                  3.10.6                   pypi_0    pypi
flit-core                 3.8.0            py39h06a4308_0
ftfy                      6.1.1                    pypi_0    pypi
huggingface-hub           0.13.3                   pypi_0    pypi
idna                      3.4                      pypi_0    pypi
intel-openmp              2023.0.0         h9e868ea_25371
joblib                    1.2.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.4.2                h6a678d5_6
libgcc-ng                 11.2.0               h1234567_1
libgomp                   11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
libuv                     1.44.2               h5eee18b_0
mkl                       2023.0.0         h6d00ec8_25399
ncurses                   6.4                  h6a678d5_0
nltk                      3.7                      pypi_0    pypi
numpy                     1.21.5                   pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0
packaging                 23.0                     pypi_0    pypi
pandas                    1.4.2                    pypi_0    pypi
pillow                    9.4.0                    pypi_0    pypi
pip                       23.0.1           py39h06a4308_0
python                    3.9.16               h7a1cb2a_2
python-dateutil           2.8.2                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.2                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
readline                  8.2                  h5eee18b_0
regex                     2023.3.23                pypi_0    pypi
requests                  2.28.2                   pypi_0    pypi
scikit-learn              1.1.1                    pypi_0    pypi
scipy                     1.10.1                   pypi_0    pypi
setuptools                65.6.3           py39h06a4308_0
simplejson                3.18.4                   pypi_0    pypi
six                       1.16.0                   pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0
tbb                       2021.7.0             hdb19cb5_0
threadpoolctl             3.1.0                    pypi_0    pypi
timm                      0.5.4                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0
tokenizers                0.12.1                   pypi_0    pypi
torch                     1.11.0                   pypi_0    pypi
torchvision               0.12.0                   pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
transformers              4.19.2                   pypi_0    pypi
typing_extensions         4.4.0            py39h06a4308_0
tzdata                    2022g                h04d1e81_0
urllib3                   1.26.15                  pypi_0    pypi
wcwidth                   0.2.6                    pypi_0    pypi
wheel                     0.38.4           py39h06a4308_0
xz                        5.2.10               h5eee18b_1
zlib                      1.2.13               h5eee18b_0

**The complete error reporting information is as follows**
Adjusting learning rate of group 0 to 1.0000e-04.
Traceback (most recent call last):
  File "/****/Visual-InCompatibility-Transformer/train_flip.py", line 79, in <module>
    train_flip(choose_image_model=choose_image_model,
  File "/****/Visual-InCompatibility-Transformer/FLIP.py", line 419, in train_flip
    loss = model_step()
  File "/****/Visual-InCompatibility-Transformer/FLIP.py", line 372, in model_step
    logits_per_image, logits_per_text = model(images, texts)
  File "/****/VITOR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/****/Visual-InCompatibility-Transformer/models.py", line 210, in forward
    x_img = self.image_encoder(images)
  File "/home/zsf/anaconda3/envs/VICTOR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zsf/anaconda3/envs/VICTOR/lib/python3.8/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/home/zsf/anaconda3/envs/VICTOR/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/zsf/anaconda3/envs/VICTOR/lib/python3.8/site-packages/torch/nn/modules/batchnorm.py", line 148, in forward
    self.num_batches_tracked.add_(1)  # type: ignore[has-type]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Process finished with exit code 1

**Comment by junedwx** [comment]
GPU is GTX3090
CUDA Version: 11.6
